language: ruby
sudo: false
rvm:
  - 2.7.0

build:
  pre_ci:
    - docker build -t ghcr.io/antoniocuadros/whentoclasstests:v2 .

  pre_ci_boot:
    image_name: ghcr.io/antoniocuadros/whentoclasstests:v2    ##replace with your repo and image name
    image_tag: latest
    pull: true
    env: FOO=bar
    options: "-e HOME=/root"
  ci:
    - ls
    - docker run -t  whentoclasstests:v2

