language: ruby
sudo: false
rvm:
  - 2.7.0

build:
  ci:
    - cd /root/src/github.com/antoniocuadros/WhenToClass
    - docker build -t whentoclasstests:v2 .
    - ls -R
    - ls 
    - pwd
    - docker run -t -v /root/src/github.com/antoniocuadros/WhenToClass:/test whentoclasstests:v2

