language: ruby
sudo: false
rvm:
  - 2.7.0
env:
  - PATH: /root/src/github.com/antoniocuadros/WhenToClass
build:
  ci:
    - cd /root/src/github.com/antoniocuadros/WhenToClass
    - docker build -t whentoclasstests:v2 .
    - ls
    - docker run -it -v `pwd`:/test whentoclasstests:v2

