language: ruby
sudo: false
rvm:
  - 2.7.0

build:
  ci:
    env:
      - PATH: /root/src/github.com/antoniocuadros/WhenToClass
    - cd /root/src/github.com/antoniocuadros/WhenToClass
    - docker build -t whentoclasstests:v2 .
    - ls
    - docker run -it -v `pwd`:/test whentoclasstests:v2

