language: ruby
sudo: false
rvm:
  - 2.7.0

build:
  ci:
    - cd /root/src/github.com/antoniocuadros/WhenToClass
    - docker build --no-cache -t whentoclasstests:v2 . 
    - ls
    - docker run -t -v `pwd`:/test whentoclasstests:v2 sh

