language: ruby
rvm:
  - 2.7.1
  - 2.7.2
  - 2.7.0
  - 2.6.0
  - 2.5.0
  - 2.4.0
  - 2.3.0

before_install:
  - gem install bundler

install: bundle install

cache:
  bundler: true
  directories:
    - /home/travis/.rvm/
    
script: rake test