language: ruby

#Cacheamos las dependencias
cache: bundler

#Probamos con distintas versiones de ruby
rvm:
  - 2.7.2
  - 2.6.0
  - 2.5.0
  - 2.4.0
  - 2.3.0

#Para poder trabajar con bundler 2.1.4
before_install:
  - gem install bundler

#Se ejecutan los tests
script: rake test