version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t whentoclasstests:v2 .
      - run: docker run -t -v `pwd`:/test whentoclasstests:v2